DROP TABLE Section_Has_Schedule;
DROP TABLE Person_Room_Schedule;
DROP TABLE Instructor_has_Schedule;
DROP TABLE Section;
DROP TABLE Course;
DROP TABLE Schedule;
DROP TABLE Equipment;
DROP TABLE Room;
DROP TABLE Person;
